version: 2

sources:
  - name: burst_bank # or burst_bank_large
    database: glue #or so many others
    tables:
      - name: account
        columns:
          - name: custkey
            data_type: VARCHAR
          - name: acctkey
            data_type: VARCHAR
          - name: products
            data_type: VARCHAR
          - name: cc_number
            data_type: VARCHAR
          - name: cc_open_date
            data_type: VARCHAR
          - name: cc_closed_date
            data_type: VARCHAR
          - name: cc_balance
            data_type: DOUBLE
          - name: cc_status
            data_type: VARCHAR
          - name: cc_default
            data_type: VARCHAR
          - name: mortgage_id
            data_type: VARCHAR
          - name: mortgage_open_date
            data_type: VARCHAR
          - name: mortgage_closed_date
            data_type: VARCHAR
          - name: mortgage_balance
            data_type: DOUBLE
          - name: mortgage_status
            data_type: VARCHAR
          - name: mortgage_default
            data_type: VARCHAR
          - name: auto_loan_id
            data_type: VARCHAR
          - name: auto_loan_open_date
            data_type: VARCHAR
          - name: auto_loan_closed_date
            data_type: VARCHAR
          - name: auto_loan_balance
            data_type: DOUBLE
          - name: auto_loan_status
            data_type: VARCHAR
          - name: auto_loan_default
            data_type: VARCHAR

      - name: auto_loan_payment
        columns:
          - name: auto_loan_id
            data_type: VARCHAR
          - name: payment_date
            data_type: VARCHAR
          - name: payment_amount
            data_type: DOUBLE
          - name: payment_due_date
            data_type: VARCHAR
          - name: delinquent_payment
            data_type: VARCHAR(1)
          - name: balance
            data_type: DOUBLE

      - name: credit_card_payment
        columns:
          - name: cc_number
            data_type: VARCHAR
          - name: payment_date
            data_type: VARCHAR
          - name: payment_amount
            data_type: DOUBLE
          - name: payment_due_date
            data_type: VARCHAR
          - name: delinquent_payment
            data_type: VARCHAR(1)
          - name: balance
            data_type: DOUBLE

      - name: customer
        columns:
          - name: custkey
            data_type: VARCHAR
          - name: first_name
            data_type: VARCHAR
          - name: last_name
            data_type: VARCHAR
          - name: street
            data_type: VARCHAR
          - name: city
            data_type: VARCHAR
          - name: state
            data_type: VARCHAR
          - name: postcode
            data_type: VARCHAR
          - name: country
            data_type: VARCHAR(2)
          - name: phone
            data_type: VARCHAR
          - name: dob
            data_type: VARCHAR
          - name: gender
            data_type: VARCHAR(1)
          - name: married
            data_type: VARCHAR(1)
          - name: ssn
            data_type: VARCHAR(11)
          - name: paycheck_dd
            data_type: VARCHAR(1)
          - name: estimated_income
            data_type: DOUBLE
          - name: fico
            data_type: INTEGER
          - name: registration_date
            data_type: VARCHAR

      - name: customer_profile
        columns:
          - name: profilekey
            data_type: VARCHAR
          - name: custkey
            data_type: VARCHAR
          - name: career
            data_type: VARCHAR
          - name: professional_status
            data_type: VARCHAR
          - name: risk_appetite
            data_type: VARCHAR
          - name: customer_segment
            data_type: VARCHAR

      - name: mortgage_payment
        columns:
          - name: mortgage_id
            data_type: VARCHAR
          - name: payment_date
            data_type: VARCHAR
          - name: payment_amount
            data_type: DOUBLE
          - name: payment_due_date
            data_type: VARCHAR
          - name: delinquent_payment
            data_type: VARCHAR(1)
          - name: balance
            data_type: DOUBLE

      - name: product_profile
        columns:
          - name: profilekey
            data_type: VARCHAR
          - name: custkey
            data_type: VARCHAR
          - name: cc_type
            data_type: VARCHAR
          - name: cc_rate
            data_type: DOUBLE
          - name: mortgage_officer
            data_type: VARCHAR
          - name: mortgage_duration
            data_type: INTEGER
          - name: mortgage_residence_type
            data_type: VARCHAR
          - name: mortgage_purchase_price
            data_type: DOUBLE
          - name: mortgage_rate
            data_type: DOUBLE
          - name: auto_loan_officer
            data_type: VARCHAR
          - name: auto_loan_duration
            data_type: INTEGER
          - name: vehicle_type
            data_type: VARCHAR
          - name: auto_purchase_price
            data_type: DOUBLE
          - name: auto_loan_rate
            data_type: DOUBLE

      - name: state_census
        columns:
          - name: sumlev
            data_type: VARCHAR
          - name: region
            data_type: VARCHAR
          - name: division
            data_type: VARCHAR
          - name: state
            data_type: VARCHAR
          - name: name
            data_type: VARCHAR
          - name: abbreviation
            data_type: VARCHAR
          - name: popestimate2019
            data_type: VARCHAR
          - name: popest18plus2019
            data_type: VARCHAR
          - name: pcnt_popest18plus
            data_type: VARCHAR
  - name: tpch
    description: Sample TPCH data
    loader: sample
    catalog: tpch
    schema: sf1  # update this to try a bigger dataset: sf100, sf1000...
    tables:
      - name: nation
        columns:
          - name: nationkey
            description: 25 nations are populated
            tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
          - name: name
          - name: regionkey
            description: Foreign Key to REGIONKEY
            tests:
              - relationships:
                  to: source('tpch', 'region')
                  field: regionkey
          - name: comment
      - name: region
        columns:
          - name: regionkey
            description: 5 regions are populated
            tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
          - name: name
          - name: comment
