version: 2

sources:
  - name: aws
    description: Sample covid data
    loader: sample
    catalog: dbt_aws_source
    schema: aws_covid_data_lake
    tables:
      - name: enigma_jhu
        columns:
          - name: fips
          - name: admin2
          - name: province_state
          - name: country_region
          - name: last_update
          - name: latitude
          - name: longitude
          - name: confirmed
          - name: deaths
          - name: recovered
          - name: active
          - name: combined_key
  - name: snowflake
    description: sample snowflake covid data
    loader: sample
    catalog: dbt_snowflake
    schema: public  # update this to try a bigger dataset: sf100, sf1000...
    tables:
      - name: owid_vaccinations
        columns:
          - name: date
          - name: country_region
          - name: iso3166_1
          - name: total_vaccinations
          - name: people_vaccinated
          - name: people_fully_vaccinated
          - name: daily_vaccinations_raw
          - name: daily_vaccinations
          - name: total_vaccinations_per_hundred
          - name: people_vaccinated_per_hundred
          - name: daily_vaccinations_per_million
          - name: vaccines
          - name: last_observation_date
          - name: source_name
          - name: source_website
          - name: last_update_date
          - name: last_reported_flag
      - name: databank_demographics
        columns:
          - name: iso3166_1
          - name: iso3166_2
          - name: fips
          - name: latitude
          - name: longitude
          - name: state
          - name: county
          - name: total_population
          - name: total_male_population
          - name: total_female_population
          - name: country_region
  - name: tpch
    description: Sample TPCH data
    loader: sample
    catalog: tpch
    schema: tiny  # update this to try a bigger dataset: sf100, sf1000...
    tables:
      - name: nation
        columns:
          - name: nationkey
            description: 25 nations are populated
            tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
          - name: name
          - name: regionkey
            description: Foreign Key to REGIONKEY
            tests:
              - relationships:
                  to: source('tpch', 'region')
                  field: regionkey
          - name: comment
      - name: region
        columns:
          - name: regionkey
            description: 5 regions are populated
            tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
          - name: name
          - name: comment
